# Generated by Django 4.0.4 on 2022-08-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyear', models.CharField(max_length=100)),
                ('eventname', models.TextField()),
                ('eventfocus', models.TextField()),
                ('eventstartdate', models.DateField()),
                ('eventenddate', models.DateField()),
                ('eventvenue', models.TextField()),
                ('eventresourceperson', models.TextField()),
                ('starttime', models.TextField()),
                ('endtime', models.TextField()),
            ],
        ),
    ]
